---
title: "lab7_assignment"
format: html
editor: visual
---

# PCA Tidyverse style

## **Data & library Import (Jeppe)**

### Import libraries

```{r}
library(tidyverse)
library(broom)  # devtools::install_github("tidymodels/broom")
library(cowplot)


```

### Import data

```{r}
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Look at the data in PC coordinates (Anton og Johan)

## Look at the variance explained by each PC (Line og Oscar)

```{r}
# Do PCA
pca_fit <- biopsy |> 
  select(where(is.numeric)) |> # retain only numeric columns
  scale() |> # scale data
  prcomp() # do PCA


pca_fit |>
  tidy(matrix = "eigenvalues")

pca_fit |>
  tidy(matrix = "eigenvalues") |>
  ggplot(aes(x = "PC", y = percent, fill = as.factor(PC), color = "black", label = scales::percent(percent))) +
  geom_bar(stat = "identity", position = "stack", alpha = 0.8, color ="black") +
  geom_text(size = 3, position = position_stack(vjust = 0.5), color = "black") +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  labs(x = "PC", y = "Percentage", fill = "PC") +
  theme(legend.position = "none")


```
